import { BsDatabaseFillGear } from "react-icons/bs";
import {
  FaHtml5,
  FaCss3Alt,
  FaJs,
  FaReact,
  FaBootstrap,
  FaGitAlt,
  FaGithub,
} from "react-icons/fa";

import {
  SiTypescript,
  SiNextdotjs,
  SiRedux,
  SiReacthookform,
  SiZod,
  SiReactquery,
  SiAxios,
  SiGoogle,
  SiTailwindcss,
  SiMui,
  SiSupabase,
  SiPrisma,
  SiFirebase,
  SiWebpack,
  SiVite,
  SiPostman,
  SiSass,
  SiShadcnui,
  SiResend,
} from "react-icons/si";
import { TbBinaryTree2 } from "react-icons/tb";

export const skills = [
  { name: "HTML5", icon: FaHtml5, color: "#E34F26" },
  { name: "CSS3", icon: FaCss3Alt, color: "#1572B6" },
  { name: "SCSS", icon: SiSass, color: "#CC6699" },
  { name: "JavaScript", icon: FaJs, color: "#F7DF1E" },
  { name: "TypeScript", icon: SiTypescript, color: "#3178C6" },
  { name: "React.js", icon: FaReact, color: "#61DAFB" },
  { name: "Next.js", icon: SiNextdotjs, color: "#FFFFFF" },
  { name: "Zustand", icon: BsDatabaseFillGear, color: "#61DAFB" },
  { name: "Redux Toolkit", icon: SiRedux, color: "#764ABC" },
  { name: "Context API", icon: TbBinaryTree2, color: "#61DAFB" },
  { name: "React Hook Form", icon: SiReacthookform, color: "#EC5990" },
  { name: "Zod", icon: SiZod, color: "#3E67B1" },
  { name: "Resend", icon: SiResend, color: "#F8FAFC" },
  { name: "React Query", icon: SiReactquery, color: "#FF4154" },
  { name: "Axios", icon: SiAxios, color: "#5A29E4" },
  { name: "RESTful APIs", icon: SiPostman, color: "#FF6C37" },
  { name: "SWR", icon: SiNextdotjs, color: "#FFFFFF" },
  { name: "NextAuth.js", icon: SiNextdotjs, color: "#FFFFFF" },
  { name: "Firebase", icon: SiFirebase, color: "#FFCA28" },
  { name: "Google OAuth", icon: SiGoogle, color: "#4285F4" },
  { name: "next-intl", icon: SiNextdotjs, color: "#FFFFFF" },
  { name: "Tailwind CSS", icon: SiTailwindcss, color: "#06B6D4" },
  { name: "Bootstrap", icon: FaBootstrap, color: "#7952B3" },
  { name: "Material UI", icon: SiMui, color: "#007FFF" },
  { name: "Shadcn UI", icon: SiShadcnui, color: "#FFFFFF" },
  { name: "Supabase", icon: SiSupabase, color: "#3ECF8E" },
  { name: "Prisma ORM", icon: SiPrisma, color: "#2D3748" },
  { name: "Git", icon: FaGitAlt, color: "#F05032" },
  { name: "GitHub", icon: FaGithub, color: "#FFFFFF" },
  { name: "Webpack", icon: SiWebpack, color: "#8DD6F9" },
  { name: "Vite", icon: SiVite, color: "#646CFF" },
  { name: "Postman", icon: SiPostman, color: "#FF6C37" },
];
